title: Julian Savini
show_downloads: true
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
